### ISSUE TITLE
Option to install from binary packages

### ISSUE THREAD

**Issue by stissot** [infertux/chef-fluentbit#2]
Building fluentbit from source may be not convenient in production environments as it requires to install a compiler and slows down the converge.
[Binary packages are provided for most Linux distros](https://docs.fluentbit.io/manual/installation/linux) by Treasure Data and that would be great to be able to configure the `install` recipe to either build from source or install from the package repository. The packages already install a systemd unit named `td-agent-bit`, so the install recipe might also skip the `systemd_unit 'fluent-bit.service'` resource in that mode.
Would you be open to this change?

**Comment by infertux** [comment]
I agree that building from source isn't ideal at all. IIRC I did that because there were no binary packages available when I created this cookbook. I'd be glad to merge such a PR if you're keen to work on it.

**Comment by infertux** [comment]
Closed by #3
